language: php
php:
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-dist

script:
  - phpunit --testsuite unit --coverage-clover=coverage.clover
  - phpunit --testsuite integration

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
